// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5VUzQpg125C9r2mesGdgHDZ04WLMEro',
    appId: '1:578118411921:web:998308e40989f8314e4130',
    messagingSenderId: '578118411921',
    projectId: 'chessmate-flutter',
    authDomain: 'chessmate-flutter.firebaseapp.com',
    storageBucket: 'chessmate-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCO5LAe-qWLIij8xOLB8zk453bJDPEhSzY',
    appId: '1:578118411921:android:f310d669210041454e4130',
    messagingSenderId: '578118411921',
    projectId: 'chessmate-flutter',
    storageBucket: 'chessmate-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_qzftxm5crBdn1wB33HFP7GVLpm1H9pg',
    appId: '1:578118411921:ios:e417ea678a2be1084e4130',
    messagingSenderId: '578118411921',
    projectId: 'chessmate-flutter',
    storageBucket: 'chessmate-flutter.firebasestorage.app',
    iosBundleId: 'com.chessmate.chessmate',
  );
}
